#!/usr/bin/env python3.11
import os
import subprocess
import getpass

ENV_FILE = "migration_env.sh"

def get_input_with_default(prompt_text, default_value, is_password=False):
    """
    Prompts the user interactively.
    If left blank, default_value is used.
    If is_password=True, input is hidden (getpass).
    All prompt functions go through this helper.
    """
    if is_password:
        user_input = getpass.getpass(f"{prompt_text} [{default_value}]: ").strip()
    else:
        user_input = input(f"{prompt_text} [{default_value}]: ").strip()

    return user_input if user_input else default_value

def setup_environment():
    """
    Collects APIC and Keycloak connection details from the user.
    Writes all values to both os.environ and migration_env.sh
    in 'export KEY="VALUE"' format.
    All subsequent scripts read this file to obtain environment variables.
    Creates ROOT_DIR if it does not exist.
    """
    print("--------------------------------------------------")
    print("STEP 1: Setting Global Environment Variables...")
    print("(Press Enter to keep the current value)")
    print("--------------------------------------------------")

    env_vars = {}
    env_vars["APIC_SERVER"] = get_input_with_default("APIC Server URL", "https://api.apic.apps.ocpinstall.gym.lan")
    env_vars["APIC_REALM"] = get_input_with_default("APIC Realm", "provider/default-idp-2")
    env_vars["PROV_ORG"] = get_input_with_default("Provider Organization", "caner-script-provider")
    env_vars["CATALOG"] = get_input_with_default("Catalog", "sandbox")
    env_vars["LOCAL_REGISTRY"] = get_input_with_default("Local Registry", "sandbox-catalog")
    env_vars["ROOT_DIR"] = get_input_with_default("Root Directory", "/home/admin/caner-script-deneme")

    print("\n--- APIC Identity and Client Information ---")
    env_vars["APIC_CLIENT_CREDS"] = get_input_with_default("Client Credentials File", "/home/admin/credentials.json")
    env_vars["APIC_USERNAME"] = get_input_with_default("APIC Admin Username", "canerkorkmaz")
    env_vars["APIC_PASSWORD"] = get_input_with_default("APIC Admin Password", "Passw0rd", is_password=True)

    print("\n--- KEYCLOAK Information ---")
    env_vars["KEYCLOAK_URL"] = get_input_with_default("KEYCLOAK URL", "http://keycloak-keycloak-demo.apps.ocpinstall.gym.lan")
    env_vars["KEYCLOAK_ADMIN_USER"] = get_input_with_default("KEYCLOAK Admin Username", "admin")
    env_vars["KEYCLOAK_ADMIN_PASSWORD"] = get_input_with_default("KEYCLOAK Admin Password", "Admin123!", is_password=True)
    env_vars["KEYCLOAK_REGISTRY_NAME"] = get_input_with_default("KEYCLOAK Registry Name", "keycluk")
    env_vars["KEYCLOAK_REALM_NAME"] = get_input_with_default("KEYCLOAK Target Realm", "apic-demo")
    env_vars["KEYCLOAK_CLIENT_ID"] = get_input_with_default("KEYCLOAK OIDC Client ID (for APIC)", "apic-client")
    env_vars["KEYCLOAK_CLIENT_SECRET"] = get_input_with_default("KEYCLOAK OIDC Client Secret (leave blank if none)", "", is_password=True)
    try:
        with open(ENV_FILE, "w") as f:
            f.write("#!/bin/bash\n")
            f.write("# This file was automatically generated by the 00_setup_env.py script.\n\n")
            for key, value in env_vars.items():
                f.write(f'export {key}="{value}"\n')
                os.environ[key] = value

        print(f"\n--> [INFO] Environment variables saved to memory and written to '{ENV_FILE}'.")

        os.makedirs(env_vars["ROOT_DIR"], exist_ok=True)
        print(f"--> [INFO] Working directory is ready: {env_vars['ROOT_DIR']}")

    except Exception as e:
        print(f"--> [ERROR] A problem occurred while setting environment variables: {str(e)}")
        exit(1)

def apic_login():
    """
    Performs a two-step login using APIC details read from os.environ:
      1. apic client-creds:set  → registers credentials.json with the APIC CLI
      2. apic login             → opens a session with server/realm/username/password
    The login token is written to the APIC CLI's own cache (~/.apiconnect/).
    All 'apic' commands in subsequent scripts will use this token.
    """
    print("\n--------------------------------------------------")
    print("STEP 2: Automatic Login to API Connect (APIC)")
    print("--------------------------------------------------")

    server = os.environ.get("APIC_SERVER")
    realm = os.environ.get("APIC_REALM")
    username = os.environ.get("APIC_USERNAME")
    password = os.environ.get("APIC_PASSWORD")
    creds_file = os.environ.get("APIC_CLIENT_CREDS")

    print(f"Target Server : {server}")
    print(f"Username      : {username}")
    print(f"Client Creds  : {creds_file}")

    # 1. Client Credentials Set Step
    print("\n--> [INFO] Setting client credentials...")
    creds_command = ["apic", "client-creds:set", creds_file]

    try:
        subprocess.run(creds_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True, check=True)
        print("--> [SUCCESS] Client credentials loaded successfully.")
    except subprocess.CalledProcessError as e:
        print("--> [ERROR] Failed to set client credentials!")
        error_details = e.stderr.strip() if e.stderr else e.stdout.strip()
        print(f"Details: {error_details}")
        exit(1)

    # 2. Login Step
    print("--> [INFO] Logging in to APIC automatically, please wait...")
    login_command = [
        "apic", "login",
        "--server", server,
        "--realm", realm,
        "--username", username,
        "--password", password
    ]

    try:
        result = subprocess.run(login_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True, check=True)
        print(f"--> [SUCCESS] {result.stdout.strip()}")

    except subprocess.CalledProcessError as e:
        print(f"--> [ERROR] APIC Login failed!")
        # If stderr is empty, check stdout (CLI errors sometimes go to stdout)
        error_details = e.stderr.strip() if e.stderr else e.stdout.strip()
        print(f"Details: {error_details}")
        exit(1)
    except FileNotFoundError:
        print("--> [ERROR] 'apic' CLI command not found! Make sure APIC Toolkit is installed and available on PATH.")
        exit(1)

if __name__ == "__main__":
    setup_environment()
    apic_login()
    print("\n==================================================")
    print("Section 1 Completed Successfully!")
    print("==================================================")
